### ISSUE TITLE
Safari

### ISSUE THREAD

**Issue by nicknikolov** [jaz303/audio-buffer-utils#13]
Hey, thanks for making this! It has been useful to me.

I just found out that Safari doesn't support any of the normal array methods on Float32Array (unless I am confused, not super familiar with typed arrays). How do you deal with this? Or have you ignored Safari for now?

Thanks

**Comment by dy** [comment]
Hi, yes, a good point. Ideally to solve that with polyfills https://github.com/Financial-Times/polyfill-service/issues/714, but as far there is no polyfills yet, i guess it needs fixing. I will have a glance.

**Comment by dy** [comment]
@nicknikolov should work now. I had to add [typedarray-methods](https://github.com/dfcreative/typedarray-methods) dependency though. Tell if it will not work.

**Comment by nicknikolov** [comment]
Nice, thanks!
