### ISSUE TITLE
Should mutating operations accept target buffer as argument?

### ISSUE THREAD

**Issue by jaz303** [jaz303/audio-buffer-utils#2]
There's no reason why operations like map(), reverse() need to work in-place; they can work equally as well with a target buffer argument

**Comment by dy** [comment]
Not sure I get what you mean. Map returns a new buffer, whereas reverse just modifies the existing one. You mean both of them could’ve returned a new buffer?

**Comment by jaz303** [comment]
Sorry map() was a wrong example; I mean it should be possible to do this:

``` javascript
var buffer1; // is a buffer;
var buffer2 = util.makeCompatible(buffer1);

// invert buffer 1, placing output in buffer 2
util.invert(buffer1, buffer2);
```

This is a common pattern used in vector/matrix libraries that allows for greater flexibility than always modifying the buffer in-place.

**Comment by dy** [comment]
Yes, immutability is a good thing, I guess. But the API consistency is even more important, according to the principle _users over authors over implementors over specifiers over theoretical purity_, because consistent API is what makes lib intuitive, no need to read docs etc.
So I think it is a good idea to make all the methods return a new buffer instead. Messing with the number of arguments is a dangerous way in JS, it is easy to bloat them and noone will ever remember the exact order.

**Comment by dy** [comment]
Thought not sure immutability is that good here. Because creation of new buffers (in browsers) is always related with allocating zero-filled memory, and it is kinda slow, taking in account the context of realtime audio processing. (if you want I’ll search references). So there we need benchmarks to decide whether it is good making API immutable.

From this standpoint I think nothing bad in letting the user decide whether she wants buffer to be cloned or not. In fact, [Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) and [TypedArray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray) methods behave in the same way - someones do clone, others don’t, and that is kind of very stable convention already, which adds points to intuitivity.

**Comment by dy** [comment]
Honestly here I stand for keeping mutability than to force creating new buffers. Modifying buffers seems to be a common practice in audio processing. For example, we can cycle [AudioSourceNode](https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode) so to play the same buffer infinitely and modify that buffer during the playback (which is done in [audio-speaker](https://github.com/audio-lab/speaker)).
Moreover, keeping methods mutable allows for agility. For user it takes nothing to clone before fill, if he needs to ensure things unchanged. But forcing creation of new buffers would disable user to use utils in mutable ways.

**Comment by dy** [comment]
@jaz303 so are we closing this issue?

**Comment by jaz303** [comment]
I don't think I've explained myself very well... will push an example to a branch tomorrow.

**Comment by dy** [comment]
@jaz303 well, anyways, if to make utils immutable, using them in `scriptProcessorNode`, for example, will be impossible, just because it requires modifying buffers, not mapping them.
Though better show examples of what you mean to understand better)

**Comment by jaz303** [comment]
To clarify what I meant here (didn't have time to make a branch today), I wasn't pushing for full immutability, rather the ability to specify an (optional) output buffer.

Example (dramatically simplified):

``` javascript
function transform(buffer, fn, outBuffer?) {
    outBuffer = outBuffer || buffer;
    buffer.eachSample(channel, offset, value) {
        outBuffer.setSample(channel, offset, fn(channel, offset, value));
    }
}
```

(This approach is used frequently in vector math libraries to provide a pool of "scratch" objects for temporary calculations)

**Comment by dy** [comment]
I see. Well, if it needs to keep stack of operations, we can do like:

``` js
fill(clone(buffer), fn);
```

Anyways, innerly that would be the same operation (checking the last `argument instanceof buffer` and cloning, if it is). Maybe some performange gain in some cases. I guess there might be a use-case for the technique you mention, we should look for it. But before not sure how reasonable to implement this.

**Comment by dy** [comment]
One hypothetical use-case is in `scriptProcessorNode`:

``` js
node.onaudioprocess = function (e) {
    util.fill(e.inputBuffer, e.outputBuffer, 2);
}
```

You’re right, for now it is impossible to easily place values to other buffer.
Except for `mix` method, which is not really obvious:

``` js
util.mix(e.outputBuffer, e.inputBuffer, function (value1, value2) { return 2});
```

Do you know what is the common pattern in arguments order for that? I’d suggest:

``` js
util.process(fromBuffer, toBuffer?, ...rest);
```

@jaz303

**Comment by dy** [comment]
@jaz303 so we have anything on this? I need the implementation of `util.clone(fromBuffer, toBuffer)`, I can do that.

**Comment by jaz303** [comment]
what are the semantics of clone() ? sounds like copy() might be a better name

**Comment by dy** [comment]
Exactly XD I was confused that `util.copy(from, to)` will be exactly the same as `util.clone(from, to)`, if we implement target buffer optional argument.

**Comment by jaz303** [comment]
cool, go with copy.

**Comment by dy** [comment]
Ok, but still. What about 2nd target arg? Are we up for that?

**Comment by jaz303** [comment]
on reflection my preference is for a method for each i.e. clone() to allocate a new one, and copy() to copy data to a pre-existing buffer. clone() becomes simply copy(foo, shallow(foo))

**Comment by dy** [comment]
Ok, but what about `reverse(from, to)`, `invert(from, to)`, `fill(from, to, how)`, `shift(from, to)`, `rotate(from, to)`, `normalize(from, to)`?
In `scriptProcessorNodes` they are almost useless in the current form:

``` js
processor.onaudioprocess = function (e) {
    var buffer = util.normalize(e.inputBuffer);
    util.copy(buffer, e.outputBuffer);
    //vs
    util.normalize(e.inputBuffer, e.outputBuffer);
}
```

**Comment by jaz303** [comment]
i guess from a consistency point of view it should be `clone(from, to?)`. are you happy with that?

**Comment by dy** [comment]
Yes, happy enough I guess) Just wanted verify that there is no misunderstanding.
So I’m going to impement `from` & `copy` methods and target optional argument for almost all current methods.
