### ISSUE TITLE
clone()'d buffers share backing array with source buffer

### ISSUE THREAD

**Issue by jaz303** [jaz303/audio-buffer-utils#3]
Cloning a buffer and then modifying data in the original buffer causes data in the clone to change also. This is due to the backing arrays being shared. Cloned buffers should be completely distinct from their source buffers.

Failing test case: https://github.com/jaz303/audio-buffer-utils/commit/97cc5fbfb19bfc4f9474a3c70341870d458dcf17

This is a result of behaviour in `audio-buffer` (not sure if intentional), which assigns a shallow copy to new derived buffers:

https://github.com/audio-lab/buffer/blob/master/buffer.js#L43-L52

**Comment by dy** [comment]
Ok, will look at

**Comment by dy** [comment]
Fixed in https://github.com/audio-lab/buffer/commit/33d29498eeee2a026c7bc44d19dfbfa91c42c686, thanks!
