### ISSUE TITLE
Cloning API

### ISSUE THREAD

**Issue by dy** [jaz303/audio-buffer-utils#4]
Now there are 3 methods doing similarly the same:
- `.slice` - returns cloned buffer of any length ≤ initial length,
- `.clone` - returns cloned buffer of the same length,
- `.makeCompatible` - returns shallow clone, same as `fill(clone(buffer))(0)` (btw how do you think maybe the name is a bit unwieldy to type?).
  So maybe there is a sense to just make `clone` method with `deep` argument, which will create a deep copy, but the shallow copy otherwise? Now clone method is lacking of use.
  In the manner of [`node.cloneNode(deep)`](https://developer.mozilla.org/en-US/docs/Web/API/Node/cloneNode) and [`npm clone`](https://www.npmjs.com/package/clone).

**Comment by jaz303** [comment]
I don't think this is a problem. I can see an argument for combining `clone` and `slice`, but `clone()` adds minimal surface area and is a little more readable so I don't see any reason to remove it.

 `makeCompatible` (which I agree is a terrible name, open to better suggestions) exists for a different reason - it means "give me a new buffer compatible with an existing buffer, _in the fastest way possible_, I don't care what data's in it". As far as possible (given that we're writing Javascript), I want `audio-buffer-utils` to be a "low level" library, so needless copying and allocation should be minimised (or eliminated entirely when possible). `makeCompatible` exists to provide the guaranteed-fastest means to create a compatible buffer in the fastest way, when the user knows they don't care about what's in it. (It's always possible to add a layer that trades efficiency for greater user-friendliness on top of something low-level, but the reverse isn't true).

**Comment by dy** [comment]
I see. Yes, clone is ok.
Some short name ideas for `makeCompatible`:
- `util.copy(buffer)` — expected to copy data, which is not true.
- `util.from(buffer)` — reminds `Array.from`, which is not the same.
- `util.new(buffer)` 
- `util.buffer(buffer)` 
- `util.empty(buffer)` 
- `util.create(buffer)` 
- `util.mimic(buffer)`
- ...

I still think that merging `makeCompatible` to `util.clone(deep)` is the best within other alternates.
At first, it adds sense and flavor to `clone` method, which now is exacly the same as `slice`.
At second, there seems to be a convention for Arrays/[TypedArrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/slice)/[ArrayBuffers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/slice)/[Buffers](https://nodejs.org/api/buffer.html#buffer_buf_slice_start_end)/[Blobs](https://developer.mozilla.org/en-US/docs/Web/API/Blob/slice)/etc objects to use `slice` to create detached clone.
Also `clone` seems to be associated with creating shallow copies, as fast as possible. E. g.:
- [`Node.cloneNode(deep)`](https://developer.mozilla.org/en-US/docs/Web/API/Node/cloneNode) introduces `deep` argument exactly in order to avoid recreating the content and creating a shallow copy of the node.
- [clone](https://www.npmjs.com/package/clone) in default config works as [shallow-clone](https://www.npmjs.com/package/shallow-clone), both of them have quite a lot of downloads, so that seems to be known behavior.

As far `clone` in this package wasn’t used much, in fact, was broken (and _is_ broken on the npm), we can safely change it’s behavior to any, all the more it will not change seriously if we set it `clone(deep)`. So what do you think?

**Comment by dy** [comment]
@jaz303 so what do you think?

**Comment by dy** [comment]
@jaz303 sorry for hurrying you up, but I need this new functionality already in related projects. Can we make a decision (I can cover implementation) and release _1.0.0_ on npm? Can you also add me to the collaborators on the npm?
Sorry once again.

**Comment by jaz303** [comment]
I don't like boolean parameters in public APIs... let's just rename makeCompatible to shallowClone ? What's your npm username?

**Comment by dy** [comment]
@dfcreative https://www.npmjs.com/~dfcreative
Maybe just `shallow` then?

**Comment by jaz303** [comment]
Added!

**Comment by dy** [comment]
:+1:
