### ISSUE TITLE
Validate AudioBuffer argument?

### ISSUE THREAD

**Issue by dy** [jaz303/audio-buffer-utils#6]
A couple of times I got into a situation where utils did something to an argument, which was not _AudioBuffer_, but for example, _Buffer_, or _Float32Array_, and silently returned something. And that led to confusion.
Validating the `argument instanceof AudioBuffer` would be handy for dev process, and that is de-facto practice, but will affect performance, a tiny bit. Should we add that @jaz303?

**Comment by jaz303** [comment]
I'm happy to add a type check. In terms of implementation, will `instanceof AudioBuffer` work correctly with buffers created by `ctx.createBuffer()`, as opposed to the  `audio-buffer` module? It's important the module works regardless of how the buffers are created.

**Comment by jaz303** [comment]
I think the right approach is to have a function `isAudioBuffer()` that checks for e.g. `typeof getChannelData == 'function'`. In the spirit of modules like `is-array` I'd be inclined to put it in its own module.

**Comment by dy** [comment]
Yes, I see. And though we can be sure that audio buffers created by [audio-buffer](https://www.npmjs.com/package/audio-buffer) package are always WebAudioAPI audio buffers in browser, for node that can be an issue, as far there is also [web-audio-api AudioBuffer](https://github.com/sebpiq/node-web-audio-api/blob/master/lib/AudioBuffer.js), which btw has also [standalone version](https://npmjs.org/package/audiobuffer), which may also want to be used with utils :)

> I'd be inclined to put it in its own module.

You mean in its own package?

**Comment by jaz303** [comment]
Sorry yes, package

**Comment by dy** [comment]
Ok, I’m on my way

**Comment by dy** [comment]
Ok, [done](https://www.npmjs.com/package/is-audio-buffer/). As far _audio-buffer-utils_ is going to be dependent on this, I’ve added you to [is-audio-buffer](https://github.com/audio-lab/is-audio-buffer) and [audio-buffer](https://github.com/audio-lab/buffer) repos.

**Comment by dy** [comment]
@jaz303  #7
